{% set version = "0.3.1" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-tinkr
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/tinkr_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/tinkr/tinkr_{{ version }}.tar.gz
  sha256: 425bc04af76483b8cf713ad141bdebb963cf54dd363fbdbee3a709820ec4d23e

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-r6
    - r-commonmark >=1.6
    - r-glue
    - r-magrittr
    - r-purrr
    - r-xml2
    - r-xslt
    - r-yaml
  run:
    - r-base
    - r-r6
    - r-commonmark >=1.6
    - r-glue
    - r-magrittr
    - r-purrr
    - r-xml2
    - r-xslt
    - r-yaml

test:
  requires:
    - r-testthat
  source_files:
    - tests/
  commands:
    - $R -e "library('tinkr')"           # [not win]
    - $R -e "testthat::test_file('tests/testthat.R', stop_on_failure=TRUE)"  # [not win]
    - "\"%R%\" -e \"library('tinkr')\""  # [win]
    - "\"%R%\" -e \"testthat::test_file('tests/testthat.R', stop_on_failure=TRUE)\""  # [win]

about:
  home: https://docs.ropensci.org/tinkr/
  dev_url: https://github.com/ropensci/tinkr
  doc_url: https://docs.ropensci.org/tinkr/
  license: GPL-3.0-or-later
  summary: Parsing '(R)Markdown' files with numerous regular expressions can be fraught with peril, but it does not have to be this way. Converting '(R)Markdown' files to 'XML' using the 'commonmark' package allows in-memory editing via of 'markdown' elements via 'XPath' through the extensible 'R6' class called 'yarn'. These
    modified 'XML' representations can be written to '(R)Markdown' documents via an 'xslt' stylesheet which implements an extended version of 'GitHub'-flavoured 'markdown' so that you can tinker to your hearts content.
  license_family: GPL3
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r
    - matthewfeickert
